In [1]:
%cd ~/REVIVAL2

/disk2/fli/REVIVAL2


In [2]:
%load_ext autoreload
%autoreload 2
%load_ext blackcellmagic

In [3]:
import numpy as np
import pandas as pd

from REVIVAL.util import get_file_name, get_dir_name, checkNgen_folder

/disk2/fli/miniconda3/envs/REVIVAL/lib/python3.11/site-packages/Bio/pairwise2.py:278: BiopythonDeprecationWarning: Bio.pairwise2 has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.PairwiseAligner as a replacement, and contact the Biopython developers if you still need the Bio.pairwise2 module.
  warnings.warn(


In [4]:
# load the npz file
npz = np.load('/disk2/fli/REVIVAL2/zs/chai/structure_seperate/ParLQ/F89A/F89A_0.npz')

In [10]:
for key in npz.files:
    print(f"Key: {key}")

Key: aggregate_score
Key: ptm
Key: iptm
Key: per_chain_ptm
Key: per_chain_pair_iptm
Key: has_inter_chain_clashes
Key: chain_chain_clashes


In [15]:
npz["per_chain_ptm"][0][0]

0.9515228

In [11]:
npz["per_chain_pair_iptm"]

array([[[0.91372466, 0.01745624, 0.6469633 ],
        [0.1678657 , 0.29231742, 0.12328164],
        [0.62215173, 0.01364201, 0.89228165]]], dtype=float32)

In [18]:
npz["per_chain_pair_iptm"][0][0, 0], npz["per_chain_pair_iptm"][0][0, 1]

(0.9515228, 0.51923597)

In [12]:
npz["has_inter_chain_clashes"]

array([False])

In [14]:
npz["chain_chain_clashes"]

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=int32)

In [7]:
for key in npz.files:
    print(f"{key}: {npz[key]}")


aggregate_score: [0.85367167]
ptm: [0.9502157]
iptm: [0.82953566]
per_chain_ptm: [[0.9515228  0.61292917]]
per_chain_pair_iptm: [[[0.9515228  0.51923597]
  [0.82953566 0.61292917]]]
has_inter_chain_clashes: [False]
chain_intra_clashes: [[0 0]]
chain_chain_inter_clashes: [[[0 0]
  [0 0]]]


In [34]:
chai_df = pd.read_csv('/disk2/fli/REVIVAL2/zs/chai/score_joint/PfTrpB-4bromo.csv')
chai_df

var  aggregate_score_0     ptm_0    iptm_0  chain_ptm_A_0  \
0    I165A:I183A:Y301V           0.909976  0.952244  0.899409       0.951416   
1    I165A:I183D:Y301L           0.900507  0.947985  0.888638       0.947609   
2    I165A:I183G:Y301C           0.911935  0.952541  0.901784       0.952170   
3    I165A:I183G:Y301L           0.903301  0.948596  0.891978       0.948001   
4    I165A:I183M:Y301N           0.909920  0.950887  0.899678       0.949977   
..                 ...                ...       ...       ...            ...   
236              Y301L           0.903126  0.950039  0.891398       0.949040   
237              Y301M           0.905885  0.950869  0.894640       0.949594   
238              Y301Q           0.905884  0.950628  0.894698       0.949423   
239              Y301T           0.910616  0.952563  0.900130       0.951637   
240              Y301V           0.908430  0.951086  0.897766       0.949813   

     chain_iptm_AB_0  chain_ptm_B_0  chain_iptm_BA_0  aggregate_score_1  \
0           0.627889       0.716868         0.899409           0.910027   
1           0.588648       0.696052         0.888638           0.901342   
2           0.614833       0.703224         0.901784           0.912532   
3           0.597885       0.697187         0.891978           0.904616   
4           0.628902       0.721188         0.899678           0.909241   
..               ...            ...              ...                ...   
236         0.626572       0.716129         0.891398           0.904172   
237         0.645468       0.730364         0.894640           0.906450   
238         0.639297       0.724331         0.894698           0.907168   
239         0.637066       0.721586         0.900130           0.911543   
240         0.643667       0.730102         0.897766           0.908792   

        ptm_1  ...  chain_iptm_AB_4  chain_ptm_B_4  chain_iptm_BA_4  \
0    0.951946  ...         0.616521       0.710465         0.899412   
1    0.948067  ...         0.600654       0.704067         0.889725   
2    0.951806  ...         0.609539       0.701333         0.903175   
3    0.948441  ...         0.595345       0.695597         0.893841   
4    0.950560  ...         0.628260       0.722302         0.898419   
..        ...  ...              ...            ...              ...   
236  0.949865  ...         0.605823       0.704857         0.891670   
237  0.951267  ...         0.641197       0.732148         0.895026   
238  0.950190  ...         0.619663       0.715540         0.896313   
239  0.952638  ...         0.621440       0.713985         0.901391   
240  0.951085  ...         0.624363       0.721030         0.897955   

     aggregate_score_avg   ptm_avg  iptm_avg  chain_ptm_A_avg  \
0               0.909753  0.952037  0.899182         0.951364   
1               0.901294  0.948175  0.889574         0.947466   
2               0.912439  0.952394  0.902451         0.952128   
3               0.904412  0.948449  0.893403         0.947995   
4               0.909463  0.950749  0.899141         0.949710   
..                   ...       ...       ...              ...   
236             0.903368  0.949973  0.891717         0.949196   
237             0.906010  0.951054  0.894749         0.949747   
238             0.906994  0.950509  0.896115         0.949457   
239             0.911037  0.952485  0.900675         0.951671   
240             0.908428  0.950901  0.897810         0.949806   

     chain_iptm_AB_avg  chain_ptm_B_avg  chain_iptm_BA_avg  
0             0.620502         0.713088           0.899182  
1             0.598549         0.701746           0.889574  
2             0.609312         0.700921           0.902451  
3             0.596192         0.696160           0.893403  
4             0.633251         0.724132           0.899141  
..                 ...              ...                ...  
236           0.616985         0.711358           0.891717  
237           0.644794         0.73

In [35]:
avg_c = [c for c in chai_df.columns if "avg" in c]
avg_c

['aggregate_score_avg',
 'ptm_avg',
 'iptm_avg',
 'chain_ptm_A_avg',
 'chain_iptm_AB_avg',
 'chain_ptm_B_avg',
 'chain_iptm_BA_avg']

In [36]:
lib_df = pd.read_csv("/disk2/fli/REVIVAL2/data/meta/not_scaled/PfTrpB-4bromo.csv")
lib_df

AAs   fitness                var  n_mut AA1 AA2 AA3  \
0    AAV -0.043328  I165A:I183A:Y301V      3   A   A   V   
1    ADL  0.061846  I165A:I183D:Y301L      3   A   D   L   
2    AGC  0.005751  I165A:I183G:Y301C      3   A   G   C   
3    AGL  0.035926  I165A:I183G:Y301L      3   A   G   L   
4    AMN -0.002284  I165A:I183M:Y301N      3   A   M   N   
..   ...       ...                ...    ...  ..  ..  ..   
236  YSQ  0.001524  I165Y:I183S:Y301Q      3   Y   S   Q   
237  YTG  0.042463  I165Y:I183T:Y301G      3   Y   T   G   
238  YTM  0.142579  I165Y:I183T:Y301M      3   Y   T   M   
239  YVA  0.097324  I165Y:I183V:Y301A      3   Y   V   A   
240  YVG  0.052566  I165Y:I183V:Y301G      3   Y   V   G   

                                                   seq  enzyme substrate  \
0    MWFGEFGGQYVPETLVGPLKELEKAYKRFKDDEEFNRQLNYYLKTW...  PfTrpB    4bromo   
1    MWFGEFGGQYVPETLVGPLKELEKAYKRFKDDEEFNRQLNYYLKTW...  PfTrpB    4bromo   
2    MWFGEFGGQYVPETLVGPLKELEKAYKRFKDDEEFNRQLNYYLKTW...  PfTrpB    4bromo   
3    MWFGEFGGQYVPETLVGPLKELEKAYKRFKDDEEFNRQLNYYLKTW...  PfTrpB    4bromo   
4    MWFGEFGGQYVPETLVGPLKELEKAYKRFKDDEEFNRQLNYYLKTW...  PfTrpB    4bromo   
..                                                 ...     ...       ...   
236  MWFGEFGGQYVPETLVGPLKELEKAYKRFKDDEEFNRQLNYYLKTW...  PfTrpB    4bromo   
237  MWFGEFGGQYVPETLVGPLKELEKAYKRFKDDEEFNRQLNYYLKTW...  PfTrpB    4bromo   
238  MWFGEFGGQYVPETLVGPLKELEKAYKRFKDDEEFNRQLNYYLKTW...  PfTrpB    4bromo   
239  MWFGEFGGQYVPETLVGPLKELEKAYKRFKDDEEFNRQLNYYLKTW...  PfTrpB    4bromo   
240  MWFGEFGGQYVPETLVGPLKELEKAYKRFKDDEEFNRQLNYYLKTW...  PfTrpB    4bromo   

            substrate-smiles                         cofactor  \
0    C1=CC2=C(C=CN2)C(=C1)Br  PLP-dependent aminoacrylate.Na+   
1    C1=CC2=C(C=CN2)C(=C1)Br  PLP-dependent aminoacrylate.Na+   
2    C1=CC2=C(C=CN2)C(=C1)Br  PLP-dependent aminoacrylate.Na+   
3    C1=CC2=C(C=CN2)C(=C1)Br  PLP-dependent aminoacrylate.Na+   
4    C1=CC2=C(C=CN2)C(=C1)Br  PLP-dependent aminoacrylate.Na+   
..                       ...                              ...   
236  C1=CC2=C(C=CN2)C(=C1)Br  PLP-dependent aminoacrylate.Na+   
237  C1=CC2=C(C=CN2)C(=C1)Br  PLP-dependent aminoacrylate.Na+   
238  C1=CC2=C(C=CN2)C(=C1)Br  PLP-dependent aminoacrylate.Na+   
239  C1=CC2=C(C=CN2)C(=C1)Br  PLP-dependent aminoacrylate.Na+   
240  C1=CC2=C(C=CN2)C(=C1)Br  PLP-dependent aminoacrylate.Na+   

                                       cofactor-smiles  \
0    [O-]C1=C(/C=[N+]([H])/C(C([O-])=O)=C)C(CP([O-]...   
1    [O-]C1=C(/C=[N+]([H])/C(C([O-])=O)=C)C(CP([O-]...   
2    [O-]C1=C(/C=[N+]([H])/C(C([O-])=O)=C)C(CP([O-]...   
3    [O-]C1=C(/C=[N+]([H])/C(C([O-])=O)=C)C(CP([O-]...   
4    [O-]C1=C(/C=[N+]([H])/C(C([O-])=O)=C)C(CP([O-]...   
..                                                 ...   
236  [O-]C1=C(/C=[N+]([H])/C(C([O-])=O)=C)C(CP([O-]...   
237  [O-]C1=C(/C=[N+]([H])/C(C([O-])=O)=C)C(CP([O-]...   
238  [O-]C1=C(/C=[N+]([H])/C(C([O-])=O)=C)C(CP([O-]...   
239  [O-]C1=C(/C=[N+]([H])/C(C([O-])=O)=C)C(CP([O-]...   
240  [O-]C1=C(/C=[N+]([H])/C(C([O-])=O)=C)C(CP([O-]...   

                                   intermediate-smiles  
0    CC1=C([O-])C(\C=[NH+]\[C@@H](CC2=CNC3=CC=CC(Br...  
1    CC1=C([O-])C(\C=[NH+]\[C@@H](CC2=CNC3=CC=CC(Br...  
2    CC1=C([O-])C(\C=[NH+]\[C@@H](CC2=CNC3=CC=CC(Br...  
3    CC1=C([O-])C(\C=[NH+]\[C@@H](CC2=CNC3=CC=CC(Br...  
4    CC1=C([O-])C(\C=[NH+]\[C@@H](CC2=CNC3=CC=CC(Br...  
..                                                 ...  
236  CC1=C([O-])C(\C=[NH+]\[C@@H](CC2=CNC3=CC=CC(Br...  
237  CC1=C([O-])C(\C=[NH+]\[C@@H](CC2=CNC3=CC=CC(Br...  
238  CC1=C([O-])C(\C=[NH+]\[C@@H](CC2=CNC3=CC=CC(Br...  
239  CC1=C([O-])C(\C=[NH+]\[C@@H](CC2=CNC3=CC=CC(Br...  
240  CC1=C([O-])C(\C=[NH+]\[C@@H](CC2=CNC3=CC=CC(Br...  

[241 rows x 14 columns]

In [37]:
merged_df = pd.merge(chai_df[["var"] + avg_c], lib_df[["var", "fitness"]], on="var", how="outer")
merged_df

var  aggregate_score_avg   ptm_avg  iptm_avg  \
0    I165A:I183A:Y301V             0.909753  0.952037  0.899182   
1    I165A:I183D:Y301L             0.901294  0.948175  0.889574   
2    I165A:I183G:Y301C             0.912439  0.952394  0.902451   
3    I165A:I183G:Y301L             0.904412  0.948449  0.893403   
4    I165A:I183M:Y301N             0.909463  0.950749  0.899141   
..                 ...                  ...       ...       ...   
236              Y301L             0.903368  0.949973  0.891717   
237              Y301M             0.906010  0.951054  0.894749   
238              Y301Q             0.906994  0.950509  0.896115   
239              Y301T             0.911037  0.952485  0.900675   
240              Y301V             0.908428  0.950901  0.897810   

     chain_ptm_A_avg  chain_iptm_AB_avg  chain_ptm_B_avg  chain_iptm_BA_avg  \
0           0.951364           0.620502         0.713088           0.899182   
1           0.947466           0.598549         0.701746           0.889574   
2           0.952128           0.609312         0.700921           0.902451   
3           0.947995           0.596192         0.696160           0.893403   
4           0.949710           0.633251         0.724132           0.899141   
..               ...                ...              ...                ...   
236         0.949196           0.616985         0.711358           0.891717   
237         0.949747           0.644794         0.732267           0.894749   
238         0.949457           0.629425         0.719737           0.896115   
239         0.951671           0.627919         0.716633           0.900675   
240         0.949806           0.632258         0.723876           0.897810   

      fitness  
0   -0.043328  
1    0.061846  
2    0.005751  
3    0.035926  
4   -0.002284  
..        ...  
236  0.182719  
237  0.110646  
238  0.135574  
239  0.176759  
240  0.172727  

[241 rows x 9 columns]

In [29]:
from scipy.stats import spearmanr  

In [30]:
for c in avg_c:
    print(c)
    print(spearmanr(merged_df["fitness"].values, merged_df[c].values))

aggregate_score_avg
SignificanceResult(statistic=np.float64(0.02058830778728312), pvalue=np.float64(0.7504936861969118))
ptm_avg
SignificanceResult(statistic=np.float64(0.06143357291588706), pvalue=np.float64(0.34229298470246494))
iptm_avg
SignificanceResult(statistic=np.float64(0.01528456065193883), pvalue=np.float64(0.8133858583945478))
has_inter_chain_clashes_avg
SignificanceResult(statistic=nan, pvalue=nan)
chain_ptm_A_avg
SignificanceResult(statistic=np.float64(0.006937783917076354), pvalue=np.float64(0.9146741910922616))
chain_iptm_AB_avg
SignificanceResult(statistic=np.float64(0.37371229308032705), pvalue=np.float64(2.1004016087181027e-09))
chain_ptm_B_avg
SignificanceResult(statistic=np.float64(0.39441033659098185), pvalue=np.float64(2.1480833665962373e-10))
chain_iptm_BA_avg
SignificanceResult(statistic=np.float64(0.01528456065193883), pvalue=np.float64(0.8133858583945478))


/tmp/ipykernel_3049277/1017786511.py:3: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  print(spearmanr(merged_df["fitness"].values, merged_df[c].values))


In [38]:
for c in avg_c:
    print(c)
    print(spearmanr(merged_df["fitness"].values, merged_df[c].values))

aggregate_score_avg
SignificanceResult(statistic=np.float64(0.02058830778728312), pvalue=np.float64(0.7504936861969118))
ptm_avg
SignificanceResult(statistic=np.float64(0.06143357291588706), pvalue=np.float64(0.34229298470246494))
iptm_avg
SignificanceResult(statistic=np.float64(0.01528456065193883), pvalue=np.float64(0.8133858583945478))
chain_ptm_A_avg
SignificanceResult(statistic=np.float64(0.006937783917076354), pvalue=np.float64(0.9146741910922616))
chain_iptm_AB_avg
SignificanceResult(statistic=np.float64(0.37371229308032705), pvalue=np.float64(2.1004016087181027e-09))
chain_ptm_B_avg
SignificanceResult(statistic=np.float64(0.39441033659098185), pvalue=np.float64(2.1480833665962373e-10))
chain_iptm_BA_avg
SignificanceResult(statistic=np.float64(0.01528456065193883), pvalue=np.float64(0.8133858583945478))
